# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html

[[constraint]]
  name = "github.com/go-playground/locales"
  version = "0.12.1"

[[constraint]]
  name = "github.com/mongodb/mongo-go-driver"
  version = "=0.0.12"

[[constraint]]
  name = "github.com/shopspring/decimal"
  version = "1.1.0"

[prune]
  go-tests = true
  unused-packages = true
